[project]
name = "ai-demo"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "anthropic==0.76.0",
    "dotenv==0.9.9",
    "gradio>=6.3.0",
    "openai==2.15.0",
]
